import type { Course } from "./types";

/**
 * B2C course catalogue. Titles/scope come from the Handover Document §10.1
 * (10 general B2C courses; Animation & VFX marked "coming soon").
 *
 * Served through the repository accessors in `./index.ts`. Phase 5 Admin CRUD
 * will move this into MongoDB behind the same interface.
 */
export const COURSES: Course[] = [
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    category: "Marketing",
    level: "All Levels",
    excerpt: "Run real campaigns across Meta, Google and WhatsApp.",
    description:
      "Master modern digital marketing the way agencies actually work — strategy, paid ads, SEO and brand building — using live briefs from Pixel Perfect Films' own clients.",
    durationWeeks: 8,
    price: 24999,
    syllabus: [
      "Marketing foundations & positioning",
      "Meta & Instagram ads",
      "Google Ads & search intent",
      "WhatsApp & funnel marketing",
      "SEO fundamentals",
      "Analytics & reporting",
    ],
    outcomes: [
      "Launch and optimise paid campaigns",
      "Build a full-funnel marketing plan",
      "Read analytics and report on ROI",
    ],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    featured: true,
  },
  {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    category: "Marketing",
    level: "Beginner",
    excerpt: "Grow audiences and build brands that people follow.",
    description:
      "Plan content calendars, craft platform-native creative, and grow engaged communities across Instagram, YouTube and LinkedIn.",
    durationWeeks: 6,
    price: 18999,
    syllabus: [
      "Platform strategy",
      "Content calendars",
      "Hooks & storytelling",
      "Community management",
      "Influencer collaborations",
    ],
    outcomes: [
      "Design a monthly content system",
      "Write scroll-stopping hooks",
      "Grow an engaged audience",
    ],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200&q=80",
  },
  {
    slug: "content-creation",
    title: "Content Creation",
    category: "Video",
    level: "Beginner",
    excerpt: "Shoot, script and ship short-form content that performs.",
    description:
      "Go from idea to published reel — scripting, shooting on a phone or camera, editing, and building a personal brand people remember.",
    durationWeeks: 4,
    price: 14999,
    syllabus: [
      "Idea to script",
      "Shooting fundamentals",
      "Short-form editing",
      "Personal branding",
    ],
    outcomes: ["Publish weekly short-form content", "Build a personal brand"],
    image: "https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=1200&q=80",
  },
  {
    slug: "video-editing",
    title: "Video Editing",
    category: "Video",
    level: "Intermediate",
    excerpt: "Cut, grade and score films like a working editor.",
    description:
      "Learn professional editing workflows — cuts, transitions, colour grading and sound design — on real footage from active productions.",
    durationWeeks: 6,
    price: 22999,
    syllabus: [
      "Editing software workflow",
      "Cuts & transitions",
      "Colour grading",
      "Sound design",
      "Export & delivery",
    ],
    outcomes: ["Edit a polished short film", "Grade footage professionally"],
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=80",
    featured: true,
  },
  {
    slug: "graphic-design",
    title: "Graphic Design",
    category: "Design",
    level: "Beginner",
    excerpt: "Design brands, social creative and marketing collateral.",
    description:
      "Build a designer's eye — typography, layout, colour and brand systems — and ship real deliverables for live briefs.",
    durationWeeks: 6,
    price: 19999,
    syllabus: ["Design principles", "Typography", "Brand systems", "Social creative"],
    outcomes: ["Design a brand identity", "Build a design portfolio"],
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&q=80",
  },
  {
    slug: "photography-cinematography",
    title: "Photography & Cinematography",
    category: "Photography",
    level: "All Levels",
    excerpt: "Master light, composition and the moving image.",
    description:
      "From stills to cinema — camera handling, lighting, composition and visual storytelling with professional gear.",
    durationWeeks: 8,
    price: 27999,
    syllabus: [
      "Camera & exposure",
      "Composition",
      "Lighting",
      "Cinematic movement",
      "Portrait & event work",
    ],
    outcomes: ["Shoot professional stills", "Light a cinematic scene"],
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&q=80",
    featured: true,
  },
  {
    slug: "ai-tools-for-creators",
    title: "AI Tools for Creators & Businesses",
    category: "AI",
    level: "All Levels",
    excerpt: "Put AI to work across content, design and marketing.",
    description:
      "Use modern AI tools to accelerate creative and marketing work — ideation, generation, editing and automation — responsibly and effectively.",
    durationWeeks: 4,
    price: 16999,
    syllabus: [
      "AI landscape for creators",
      "Prompting for content",
      "AI in design & video",
      "Workflow automation",
    ],
    outcomes: ["Build an AI-assisted workflow", "Ship faster with AI"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&q=80",
  },
  {
    slug: "website-design-development",
    title: "Website Design & Development",
    category: "Development",
    level: "Intermediate",
    excerpt: "Design and build fast, modern websites.",
    description:
      "Learn to design and build responsive, modern websites — from layout and UX to shipping a live site.",
    durationWeeks: 8,
    price: 29999,
    syllabus: ["Web design fundamentals", "Responsive layout", "No-code & code", "Launch"],
    outcomes: ["Design a modern website", "Ship a live site"],
    image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&q=80",
  },
  {
    slug: "film-making",
    title: "Film Making",
    category: "Film",
    level: "Intermediate",
    excerpt: "Direct a film end-to-end, from script to screen.",
    description:
      "The complete filmmaking journey — story, direction, production and post — mentored by working filmmakers on real sets.",
    durationWeeks: 10,
    price: 34999,
    syllabus: [
      "Storytelling & script",
      "Direction",
      "Production planning",
      "On-set craft",
      "Post & delivery",
    ],
    outcomes: ["Direct a short film", "Build a director's reel"],
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80",
    featured: true,
  },
  {
    slug: "animation-vfx",
    title: "Animation & VFX",
    category: "Video",
    level: "Intermediate",
    excerpt: "Motion graphics and visual effects — coming soon.",
    description:
      "A dedicated animation and visual effects track is coming soon. Register your interest to be notified when enrolment opens.",
    durationWeeks: 8,
    price: 0,
    syllabus: ["Motion graphics", "Compositing", "VFX fundamentals"],
    outcomes: ["Create motion graphics", "Composite visual effects"],
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    comingSoon: true,
  },
];
